### ISSUE TITLE
tvOS support not released

### ISSUE THREAD

**Issue by Tagir-A** [kevinresol/react-native-default-preference#53]
Hello,

I noticed that for some reason the `.podspec` file in the release **1.4.1** doesn't contain `tvOS` as one of the targets.
That results in an annoying error while using the package.
The fix is already there in the repo, but for some reason, it's not included in the released archive.

Could you tell why?

**Comment by marcelkalveram** [comment]
Hey @Tagir-A . I hadn't published the version that included that fix on npm. I just bumped the version to 1.4.2. with all recent changes since https://github.com/kevinresol/react-native-default-preference/commit/96764cb495debc70cefab3db711ba10a3847b7d6.

Sorry for the delay and thanks for the nudge!
